# Generated by Django 5.1.15 on 2026-02-16 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название кампании')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'В работе'), ('paused', 'Приостановлена'), ('completed', 'Завершена')], default='draft', max_length=20, verbose_name='Статус')),
                ('hypothesis', models.TextField(blank=True, verbose_name='Гипотеза')),
                ('hypothesis_result', models.TextField(blank=True, verbose_name='Результат проверки гипотезы')),
                ('forecast_demand', models.IntegerField(blank=True, null=True, verbose_name='Прогноз потребности (чел.)')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('federal_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='reference.federaloperator', verbose_name='Федеральный оператор')),
            ],
            options={
                'verbose_name': 'Кампания',
                'verbose_name_plural': 'Кампании',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.IntegerField(verbose_name='Номер очереди')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название очереди')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='campaigns.campaign', verbose_name='Кампания')),
            ],
            options={
                'verbose_name': 'Очередь кампании',
                'verbose_name_plural': 'Очереди кампании',
                'ordering': ['queue_number'],
                'unique_together': {('campaign', 'queue_number')},
            },
        ),
        migrations.CreateModel(
            name='CampaignOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('contacted', 'Связались'), ('interested', 'Заинтересован'), ('declined', 'Отказ'), ('demand_received', 'Потребность получена')], default='pending', max_length=20, verbose_name='Статус')),
                ('demand_count', models.IntegerField(default=0, verbose_name='Заявленная потребность (чел.)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='campaigns.campaign', verbose_name='Кампания')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_campaign_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_entries', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Организация в кампании',
                'verbose_name_plural': 'Организации в кампании',
                'unique_together': {('campaign', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='CampaignProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_programs', to='campaigns.campaign', verbose_name='Кампания')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_campaign_programs', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_entries', to='reference.program', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Программа в кампании',
                'verbose_name_plural': 'Программы в кампании',
                'unique_together': {('campaign', 'program')},
            },
        ),
        migrations.CreateModel(
            name='CampaignRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_regions', to='campaigns.campaign', verbose_name='Кампания')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_campaign_regions', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='campaigns.campaignqueue', verbose_name='Очередь')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_entries', to='reference.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Регион в кампании',
                'verbose_name_plural': 'Регионы в кампании',
                'unique_together': {('campaign', 'region')},
            },
        ),
    ]
