# Generated by Django 5.2.9 on 2026-03-12 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('funnels', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='forecast_demand',
        ),
        migrations.CreateModel(
            name='CampaignFunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_funnels', to='campaigns.campaign', verbose_name='Кампания')),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_funnels', to='funnels.funnel', verbose_name='Воронка')),
            ],
            options={
                'verbose_name': 'Воронка в кампании',
                'verbose_name_plural': 'Воронки в кампании',
                'unique_together': {('campaign', 'funnel')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='funnels',
            field=models.ManyToManyField(blank=True, related_name='campaigns', through='campaigns.CampaignFunnel', to='funnels.funnel', verbose_name='Воронки'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_demand', models.IntegerField(blank=True, null=True, verbose_name='Прогноз потребности (чел.)')),
                ('demand_count', models.IntegerField(default=0, verbose_name='Фактическая потребность (чел.)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='campaigns.campaign', verbose_name='Кампания')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_leads', to='funnels.funnelstage', verbose_name='Текущая стадия')),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='funnels.funnel', verbose_name='Воронка')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_leads', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='organizations.organization', verbose_name='Организация')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='campaigns.campaignqueue', verbose_name='Очередь')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'organization', 'funnel')},
            },
        ),
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=300, verbose_name='С кем общались')),
                ('contact_position', models.CharField(blank=True, max_length=300, verbose_name='Должность')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Телефон'), ('meeting', 'Встреча'), ('messenger', 'Мессенджер'), ('letter', 'Письмо'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Канал')),
                ('result', models.TextField(blank=True, verbose_name='Результат')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='campaigns.lead', verbose_name='Лид')),
            ],
            options={
                'verbose_name': 'Взаимодействие по лиду',
                'verbose_name_plural': 'Взаимодействия по лидам',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LeadChecklistValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('text_value', models.TextField(blank=True, verbose_name='Текстовое значение')),
                ('file_value', models.FileField(blank=True, upload_to='lead_files/', verbose_name='Файл')),
                ('select_value', models.CharField(blank=True, max_length=300, verbose_name='Выбранное значение')),
                ('contact_name', models.CharField(blank=True, max_length=300, verbose_name='ФИО контакта')),
                ('contact_position', models.CharField(blank=True, max_length=300, verbose_name='Должность')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_messenger', models.CharField(blank=True, max_length=300, verbose_name='Мессенджер')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_values', to='funnels.stagechecklistitem', verbose_name='Пункт чек-листа')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Выполнил')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_values', to='campaigns.lead', verbose_name='Лид')),
            ],
            options={
                'verbose_name': 'Значение чек-листа лида',
                'verbose_name_plural': 'Значения чек-листа лидов',
                'unique_together': {('lead', 'checklist_item')},
            },
        ),
        migrations.CreateModel(
            name='QueueStageDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_days', models.PositiveIntegerField(verbose_name='Дедлайн (раб. дней от старта очереди)')),
                ('funnel_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_deadlines', to='funnels.funnelstage', verbose_name='Стадия воронки')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_deadlines', to='campaigns.campaignqueue', verbose_name='Очередь')),
            ],
            options={
                'verbose_name': 'Дедлайн стадии в очереди',
                'verbose_name_plural': 'Дедлайны стадий в очередях',
                'unique_together': {('queue', 'funnel_stage')},
            },
        ),
    ]
