# Generated by Django 5.1.15 on 2026-03-16 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_remove_campaign_deadline_and_more'),
        ('organizations', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadchecklistvalue',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_values', to='organizations.contact', verbose_name='Контакт'),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_interactions', to='organizations.contact', verbose_name='Контакт'),
        ),
    ]
