# Generated by Django 5.1.15 on 2026-06-01 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from config.migration_helpers import AddFieldIfNotExists, CreateModelIfNotExists


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_leadsubfunnel_workflow_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateModelIfNotExists(
            name='CampaignSubfunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_version', models.PositiveIntegerField(default=1, verbose_name='Версия шаблона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Подворонка кампании',
                'verbose_name_plural': 'Подворонки кампаний',
                'ordering': ['campaign_id', 'id'],
            },
        ),
        CreateModelIfNotExists(
            name='LeadSubfunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('backlog', 'Бэклог'), ('in_progress', 'В работе'), ('paused', 'Пауза'), ('rejected', 'Отказ'), ('done', 'Готово'), ('todo', 'К выполнению'), ('blocked', 'Блокировано')], default='backlog', max_length=30, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Старт')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('is_available', models.BooleanField(default=True, help_text='Для диапазонных подворонок availability вычисляется по стадии лида.', verbose_name='Доступна на текущей стадии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Подворонка лида',
                'verbose_name_plural': 'Подворонки лидов',
                'ordering': ['-updated_at'],
            },
        ),
        CreateModelIfNotExists(
            name='LeadSubfunnelChecklistValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('text_value', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда выполнен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Значение чек-листа подворонки',
                'verbose_name_plural': 'Значения чек-листа подворонки',
                'ordering': ['template_item__order', 'id'],
            },
        ),
        AddFieldIfNotExists(
            model_name='campaign',
            name='collect_search_task',
            field=models.TextField(blank=True, default='', help_text='Краткий бриф по типу организаций и контактов для стадии сбора лидов', verbose_name='Задание на поиск'),
        ),
        AddFieldIfNotExists(
            model_name='campaign',
            name='operational_stage',
            field=models.CharField(blank=True, choices=[('organization_list', 'Формирование перечня организаций')], default='', help_text='Операционная стадия жизненного цикла кампании (отдельно от статуса и стадий воронки лидов)', max_length=40, verbose_name='Стадия кампании'),
        ),
        AddFieldIfNotExists(
            model_name='campaignregion',
            name='demand_quota',
            field=models.PositiveIntegerField(default=0, verbose_name='Квота региона (чел.)'),
        ),
        AddFieldIfNotExists(
            model_name='campaignregion',
            name='primary_contact_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist_campaign_regions', to=settings.AUTH_USER_MODEL, verbose_name='Специалист по первичному контакту'),
        ),
        AddFieldIfNotExists(
            model_name='campaignregion',
            name='search_task',
            field=models.TextField(blank=True, default='', verbose_name='Задание на поиск в регионе'),
        ),
        AddFieldIfNotExists(
            model_name='lead',
            name='primary_contact_result',
            field=models.TextField(blank=True, default='', verbose_name='Результат первичного контакта'),
        ),
        AddFieldIfNotExists(
            model_name='lead',
            name='primary_contact_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist_leads', to=settings.AUTH_USER_MODEL, verbose_name='Специалист по первичному контакту'),
        ),
        AddFieldIfNotExists(
            model_name='lead',
            name='primary_contact_status',
            field=models.CharField(choices=[('new', 'Новый'), ('email_prepared', 'Письмо подготовлено'), ('email_sent', 'Письмо отправлено'), ('response_received', 'Ответ получен'), ('result_recorded', 'Результат зафиксирован'), ('rejected', 'Отказ')], default='new', max_length=30, verbose_name='Статус первичного контакта'),
        ),
        AddFieldIfNotExists(
            model_name='leadchecklistvalue',
            name='primary_contact_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist_checklist_values', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный специалист'),
        ),
    ]
