# Generated by Django 5.1.15 on 2026-06-01 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from config.migration_helpers import AddConstraintIfNotExists, AddFieldIfNotExists


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_definition'),
        ('campaigns', '0013_campaignsubfunnel_leadsubfunnel_and_more'),
        ('funnels', '0013_subfunneltemplate_subfunneltemplatebinding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name='campaignsubfunnel',
            name='binding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_subfunnels', to='funnels.subfunneltemplatebinding', verbose_name='Привязка шаблона'),
        ),
        AddFieldIfNotExists(
            model_name='campaignsubfunnel',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfunnels', to='campaigns.campaign', verbose_name='Кампания'),
        ),
        AddFieldIfNotExists(
            model_name='campaignsubfunnel',
            name='default_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_subfunnels_default_assignee', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель по умолчанию'),
        ),
        AddFieldIfNotExists(
            model_name='campaignsubfunnel',
            name='funnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_subfunnels', to='funnels.funnel', verbose_name='Основная воронка'),
        ),
        AddFieldIfNotExists(
            model_name='campaignsubfunnel',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_subfunnels', to='accounts.roledefinition', verbose_name='Роль'),
        ),
        AddFieldIfNotExists(
            model_name='campaignsubfunnel',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_subfunnels', to='funnels.subfunneltemplate', verbose_name='Шаблон подворонки'),
        ),
        AddFieldIfNotExists(
            model_name='leadsubfunnel',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_subfunnels_assignee', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        AddFieldIfNotExists(
            model_name='leadsubfunnel',
            name='campaign_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_tasks', to='campaigns.campaignregion', verbose_name='Регион кампании'),
        ),
        AddFieldIfNotExists(
            model_name='leadsubfunnel',
            name='campaign_subfunnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_subfunnels', to='campaigns.campaignsubfunnel', verbose_name='Подворонка кампании'),
        ),
        AddFieldIfNotExists(
            model_name='leadsubfunnel',
            name='current_template_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_subfunnels', to='funnels.tasktemplatestage', verbose_name='Текущий этап шаблона задачи'),
        ),
        AddFieldIfNotExists(
            model_name='leadsubfunnel',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfunnels', to='campaigns.lead', verbose_name='Лид'),
        ),
        AddFieldIfNotExists(
            model_name='leadsubfunnelchecklistvalue',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lead_subfunnel_values', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель пункта'),
        ),
        AddFieldIfNotExists(
            model_name='leadsubfunnelchecklistvalue',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_lead_subfunnel_values', to=settings.AUTH_USER_MODEL, verbose_name='Кем выполнен'),
        ),
        AddFieldIfNotExists(
            model_name='leadsubfunnelchecklistvalue',
            name='lead_subfunnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_values', to='campaigns.leadsubfunnel', verbose_name='Подворонка лида'),
        ),
        AddFieldIfNotExists(
            model_name='leadsubfunnelchecklistvalue',
            name='template_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_values', to='funnels.subfunneltemplateitem', verbose_name='Пункт шаблона'),
        ),
        AddConstraintIfNotExists(
            model_name='campaignsubfunnel',
            constraint=models.UniqueConstraint(fields=('campaign', 'template', 'binding'), name='unique_campaign_subfunnel_template_binding'),
        ),
        AddConstraintIfNotExists(
            model_name='leadsubfunnel',
            constraint=models.UniqueConstraint(condition=models.Q(('lead__isnull', False)), fields=('campaign_subfunnel', 'lead'), name='unique_lead_subfunnel_per_campaign_subfunnel'),
        ),
        AddConstraintIfNotExists(
            model_name='leadsubfunnel',
            constraint=models.UniqueConstraint(condition=models.Q(('campaign_region__isnull', False)), fields=('campaign_subfunnel', 'campaign_region'), name='unique_region_subfunnel_per_campaign_subfunnel'),
        ),
        AddConstraintIfNotExists(
            model_name='leadsubfunnel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('campaign_region__isnull', True), ('lead__isnull', False)), models.Q(('campaign_region__isnull', False), ('lead__isnull', True)), _connector='OR'), name='lead_subfunnel_lead_xor_campaign_region'),
        ),
        AddConstraintIfNotExists(
            model_name='leadsubfunnelchecklistvalue',
            constraint=models.UniqueConstraint(fields=('lead_subfunnel', 'template_item'), name='unique_lead_subfunnel_template_item_value'),
        ),
    ]
