# Generated by Django 5.2.9 on 2026-03-12 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название воронки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Воронка',
                'verbose_name_plural': 'Воронки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FunnelStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название стадии')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('deadline_days', models.PositiveIntegerField(default=0, help_text='Количество рабочих дней от даты старта очереди', verbose_name='Дедлайн (раб. дней от старта)')),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='funnels.funnel', verbose_name='Воронка')),
            ],
            options={
                'verbose_name': 'Стадия воронки',
                'verbose_name_plural': 'Стадии воронки',
                'ordering': ['order'],
                'unique_together': {('funnel', 'order')},
            },
        ),
        migrations.CreateModel(
            name='StageChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст пункта')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('confirmation_type', models.CharField(choices=[('none', 'Без подтверждения'), ('text', 'Текст'), ('file', 'Файл(ы)'), ('select', 'Выбор из списка'), ('contact', 'Контакт')], default='none', max_length=20, verbose_name='Тип подтверждения')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='funnels.funnelstage', verbose_name='Стадия')),
            ],
            options={
                'verbose_name': 'Пункт чек-листа',
                'verbose_name_plural': 'Пункты чек-листа',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='funnels.stagechecklistitem', verbose_name='Пункт чек-листа')),
            ],
            options={
                'verbose_name': 'Вариант выбора',
                'verbose_name_plural': 'Варианты выбора',
                'ordering': ['order'],
            },
        ),
    ]
