# Generated by Django 5.1.15 on 2026-03-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funnelstage',
            name='is_rejection',
            field=models.BooleanField(default=False, help_text='Специальная стадия, на которую можно перейти из любой другой', verbose_name='Стадия отказа'),
        ),
    ]
