# Generated by Django 5.1.15 on 2026-05-19 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0011_add_organization_list_stage_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnelstage',
            name='primary_contact_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_contact_funnel_stages', to=settings.AUTH_USER_MODEL, verbose_name='Специалист по умолчанию'),
        ),
    ]
