# Generated by Django 5.1.15 on 2026-06-01 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from config.migration_helpers import (
    AddConstraintIfNotExists,
    AddFieldIfNotExists,
    AlterUniqueTogetherIfNotExists,
    CreateModelIfNotExists,
)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_role_definition"),
        ("funnels", "0012_alter_funnelstage_primary_contact_specialist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateModelIfNotExists(
            name="SubfunnelTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=300, verbose_name="Название подворонки")),
                ("slug", models.SlugField(max_length=120, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, default="", verbose_name="Описание")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                ("version", models.PositiveIntegerField(default=1, verbose_name="Версия шаблона")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Шаблон подворонки",
                "verbose_name_plural": "Шаблоны подворонок",
                "ordering": ["name"],
            },
        ),
        CreateModelIfNotExists(
            name="SubfunnelTemplateBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "binding_type",
                    models.CharField(
                        choices=[
                            ("stage", "К стадии"),
                            ("checklist_item", "К пункту чек-листа"),
                            ("stage_range_checklist", "К диапазону стадий"),
                        ],
                        default="checklist_item",
                        max_length=40,
                        verbose_name="Тип привязки",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Привязка шаблона подворонки",
                "verbose_name_plural": "Привязки шаблонов подворонок",
                "ordering": ["funnel_id", "id"],
            },
        ),
        CreateModelIfNotExists(
            name="SubfunnelTemplateItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=300, verbose_name="Название пункта")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                (
                    "execution_type",
                    models.CharField(
                        choices=[
                            ("stage", "Отдельная стадия"),
                            ("checklist_item", "Пункт чек-листа"),
                            ("stage_range_checklist", "Чек-лист диапазона стадий"),
                        ],
                        default="checklist_item",
                        max_length=40,
                        verbose_name="Тип исполнения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт шаблона подворонки",
                "verbose_name_plural": "Пункты шаблона подворонки",
                "ordering": ["order", "id"],
            },
        ),
        CreateModelIfNotExists(
            name="TaskTemplateStage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Название этапа")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("is_terminal", models.BooleanField(default=False, verbose_name="Финальный этап")),
                ("sla_days", models.PositiveIntegerField(default=0, verbose_name="SLA (дней)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Этап шаблона задачи",
                "verbose_name_plural": "Этапы шаблона задачи",
                "ordering": ["order", "id"],
            },
        ),
        AddFieldIfNotExists(
            model_name="funnelstage",
            name="is_collect_stage",
            field=models.BooleanField(
                default=False,
                help_text="Опциональная нулевая стадия предварительного сбора лидов",
                verbose_name="Стадия сбора и добавления лидов",
            ),
        ),
        AddFieldIfNotExists(
            model_name="funnelstage",
            name="responsible_role",
            field=models.CharField(
                choices=[
                    ("manager", "Менеджер"),
                    ("primary_contact_specialist", "Специалист по первичному контакту"),
                ],
                default="manager",
                help_text="Роль, которая по умолчанию отвечает за выполнение этапа",
                max_length=40,
                verbose_name="Роль этапа",
            ),
        ),
        AddFieldIfNotExists(
            model_name="funnelstage",
            name="search_task",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Краткое описание типа организаций и контактов для первичного поиска",
                verbose_name="Задание на поиск",
            ),
        ),
        AddFieldIfNotExists(
            model_name="funnelstage",
            name="selection_mode",
            field=models.CharField(
                blank=True,
                choices=[("regions", "Регионы")],
                default="",
                max_length=20,
                verbose_name="Режим отбора",
            ),
        ),
        AddFieldIfNotExists(
            model_name="stagechecklistitem",
            name="communication_step",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Без шага"),
                    ("email_prepared", "Письмо подготовлено"),
                    ("email_sent", "Письмо отправлено"),
                    ("response_received", "Ответ получен"),
                    ("result_recorded", "Результат зафиксирован"),
                ],
                default="",
                max_length=40,
                verbose_name="Шаг коммуникации",
            ),
        ),
        AddFieldIfNotExists(
            model_name="stagechecklistitem",
            name="primary_contact_specialist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_contact_checklist_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Специалист по первичному контакту",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="funnelstage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_collect_stage", True)),
                fields=("funnel",),
                name="funnel_single_collect_stage",
            ),
        ),
        AddFieldIfNotExists(
            model_name="subfunneltemplate",
            name="owner_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_subfunnel_templates",
                to="accounts.roledefinition",
                verbose_name="Базовая роль-владелец",
            ),
        ),
        AddFieldIfNotExists(
            model_name="subfunneltemplatebinding",
            name="default_specialist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subfunnel_bindings_default_specialist",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Специалист по умолчанию",
            ),
        ),
        AddFieldIfNotExists(
            model_name="subfunneltemplatebinding",
            name="from_stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subfunnel_bindings_as_from_stage",
                to="funnels.funnelstage",
                verbose_name="Стадия начала диапазона",
            ),
        ),
        AddFieldIfNotExists(
            model_name="subfunneltemplatebinding",
            name="funnel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subfunnel_bindings",
                to="funnels.funnel",
                verbose_name="Основная воронка",
            ),
        ),
        AddFieldIfNotExists(
            model_name="subfunneltemplatebinding",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subfunnel_bindings",
                to="accounts.roledefinition",
                verbose_name="Роль",
            ),
        ),
        AddFieldIfNotExists(
            model_name="subfunneltemplatebinding",
            name="target_checklist_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subfunnel_bindings_as_checklist_item",
                to="funnels.stagechecklistitem",
                verbose_name="Целевой пункт чек-листа",
            ),
        ),
        AddFieldIfNotExists(
            model_name="subfunneltemplatebinding",
            name="target_stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subfunnel_bindings_as_stage",
                to="funnels.funnelstage",
                verbose_name="Целевая стадия",
            ),
        ),
        AddFieldIfNotExists(
            model_name="subfunneltemplatebinding",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bindings",
                to="funnels.subfunneltemplate",
                verbose_name="Шаблон подворонки",
            ),
        ),
        AddFieldIfNotExists(
            model_name="subfunneltemplatebinding",
            name="to_stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subfunnel_bindings_as_to_stage",
                to="funnels.funnelstage",
                verbose_name="Стадия окончания диапазона",
            ),
        ),
        AddFieldIfNotExists(
            model_name="subfunneltemplateitem",
            name="default_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_subfunnel_template_items",
                to="accounts.roledefinition",
                verbose_name="Роль по умолчанию",
            ),
        ),
        AddFieldIfNotExists(
            model_name="subfunneltemplateitem",
            name="default_specialist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_subfunnel_template_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Специалист по умолчанию",
            ),
        ),
        AddFieldIfNotExists(
            model_name="subfunneltemplateitem",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="funnels.subfunneltemplate",
                verbose_name="Шаблон подворонки",
            ),
        ),
        AddFieldIfNotExists(
            model_name="tasktemplatestage",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="funnels.subfunneltemplate",
                verbose_name="Шаблон задачи",
            ),
        ),
        AddFieldIfNotExists(
            model_name="subfunneltemplateitem",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="funnels.tasktemplatestage",
                verbose_name="Этап задачи",
            ),
        ),
        AlterUniqueTogetherIfNotExists(
            name="tasktemplatestage",
            unique_together={("template", "order")},
        ),
    ]
