# Generated by Django 5.1.15 on 2026-02-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FederalDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('short_name', models.CharField(blank=True, max_length=10, verbose_name='Сокращение')),
            ],
            options={
                'verbose_name': 'Федеральный округ',
                'verbose_name_plural': 'Федеральные округа',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FederalOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Федеральный оператор',
                'verbose_name_plural': 'Федеральные операторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер в перечне')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование профессии')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Номер договора')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('status', models.CharField(choices=[('draft', 'Проект'), ('active', 'Действующий'), ('completed', 'Завершён')], default='draft', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('federal_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='reference.federaloperator', verbose_name='Федеральный оператор')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-year', 'federal_operator'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование программы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('hours', models.IntegerField(blank=True, null=True, verbose_name='Часов обучения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='reference.profession', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Программа обучения',
                'verbose_name_plural': 'Программы обучения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Код')),
                ('federal_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='reference.federaldistrict', verbose_name='Федеральный округ')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2026, verbose_name='Год')),
                ('total', models.IntegerField(default=0, verbose_name='Всего квота')),
                ('used', models.IntegerField(default=0, verbose_name='Использовано')),
                ('federal_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='reference.federaloperator', verbose_name='Федеральный оператор')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='reference.program', verbose_name='Программа')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='reference.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Квота',
                'verbose_name_plural': 'Квоты',
            },
        ),
        migrations.CreateModel(
            name='ContractProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft_appendix', 'В проекте приложения'), ('in_appendix', 'В приложении'), ('approved', 'Утверждена')], default='draft_appendix', max_length=20, verbose_name='Статус в договоре')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='reference.contract', verbose_name='Договор')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_entries', to='reference.program', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Программа в договоре',
                'verbose_name_plural': 'Программы в договорах',
                'unique_together': {('contract', 'program')},
            },
        ),
        migrations.CreateModel(
            name='ProfessionDemandStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demanded', models.BooleanField(default=False, verbose_name='Востребована')),
                ('year', models.IntegerField(default=2026, verbose_name='Год')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_statuses', to='reference.profession', verbose_name='Профессия')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_statuses', to='reference.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Востребованность профессии',
                'verbose_name_plural': 'Востребованность профессий',
                'unique_together': {('profession', 'region', 'year')},
            },
        ),
    ]
