# Generated by Django 5.1.15 on 2026-02-17 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionApprovalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2026, verbose_name='Год')),
                ('approval_status', models.CharField(choices=[('pending', 'Ожидает'), ('preliminary_approved', 'Предварительно одобрено'), ('approved', 'Одобрено (по факту потока)'), ('rejected', 'Отказано'), ('unlikely', 'Маловероятно')], default='pending', max_length=30, verbose_name='Статус одобрения')),
                ('approved_date', models.DateField(blank=True, null=True, verbose_name='Дата одобрения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_statuses', to='reference.profession', verbose_name='Профессия')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_statuses', to='reference.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Статус одобрения профессии',
                'verbose_name_plural': 'Статусы одобрения профессий',
                'unique_together': {('profession', 'region', 'year')},
            },
        ),
    ]
