# Generated by Django 5.1.15 on 2026-02-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_professionapprovalstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionapprovalstatus',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В проработке'), ('preliminary_approved', 'Предварительно одобрено'), ('approved', 'Одобрено (по факту потока)'), ('rejected', 'Отказано'), ('unlikely', 'Маловероятно')], default='pending', max_length=30, verbose_name='Статус одобрения'),
        ),
    ]
