# Generated by Django 5.1.15

from django.db import migrations, models


def fill_short_name_from_name(apps, schema_editor):
    FederalOperator = apps.get_model("reference", "FederalOperator")
    for op in FederalOperator.objects.all():
        if not op.short_name:
            op.short_name = op.name[:150] if len(op.name) > 150 else op.name
            op.save()


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0003_alter_professionapprovalstatus_approval_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="federaloperator",
            name="short_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="Сокращённое название",
            ),
        ),
        migrations.RunPython(fill_short_name_from_name, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="federaloperator",
            name="code",
        ),
    ]
