# Generated by Django 5.1.15

from django.db import migrations, models
import django.db.models.deletion


def set_federal_operator(apps, schema_editor):
    FederalOperator = apps.get_model("reference", "FederalOperator")
    ProfessionDemandStatus = apps.get_model("reference", "ProfessionDemandStatus")
    first = FederalOperator.objects.order_by("id").first()
    if first:
        ProfessionDemandStatus.objects.update(federal_operator=first)


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0004_federaloperator_short_name_remove_federaloperator_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="professiondemandstatus",
            name="federal_operator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demand_statuses",
                to="reference.federaloperator",
                verbose_name="Федеральный оператор",
            ),
        ),
        migrations.RunPython(set_federal_operator, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="professiondemandstatus",
            name="federal_operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demand_statuses",
                to="reference.federaloperator",
                verbose_name="Федеральный оператор",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="professiondemandstatus",
            unique_together={("federal_operator", "profession", "region", "year")},
        ),
    ]
