# Generated by Django 5.1.15 on 2026-02-26 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_professiondemandstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата импорта')),
                ('snapshot_count', models.PositiveIntegerField(default=0, verbose_name='Записей в снимке')),
                ('federal_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_imports', to='reference.federaloperator', verbose_name='Федеральный оператор')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_imports', to=settings.AUTH_USER_MODEL, verbose_name='Импортировал')),
            ],
            options={
                'verbose_name': 'Импорт востребованности',
                'verbose_name_plural': 'Импорты востребованности',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandImportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demanded', models.BooleanField(verbose_name='Востребована')),
                ('demand_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='reference.demandimport', verbose_name='Импорт')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reference.profession', verbose_name='Профессия')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reference.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Снимок востребованности',
                'verbose_name_plural': 'Снимки востребованности',
                'unique_together': {('demand_import', 'profession', 'region')},
            },
        ),
    ]
