# Generated by Django 5.1.15 on 2026-02-16 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, max_length=200, verbose_name='Краткое наименование')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('org_type', models.CharField(choices=[('ministry', 'Министерство/ведомство'), ('enterprise', 'Предприятие'), ('education', 'Образовательная организация'), ('healthcare', 'Учреждение здравоохранения'), ('municipal', 'Муниципальное учреждение'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип организации')),
                ('contact_person', models.CharField(blank=True, max_length=300, verbose_name='Контактное лицо')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='organizations.organization', verbose_name='Головная организация')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='reference.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('interaction_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Телефонный звонок'), ('meeting', 'Встреча'), ('letter', 'Письмо'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип взаимодействия')),
                ('notes', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='organizations.organization', verbose_name='Организация')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Взаимодействие',
                'verbose_name_plural': 'История взаимодействий',
                'ordering': ['-date'],
            },
        ),
    ]
