# Generated by Django 5.1.15 on 2026-03-16 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('person', 'Физическое лицо'), ('department', 'Отдел'), ('main', 'Основной'), ('other', 'Другое')], default='person', max_length=20, verbose_name='Тип контакта')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('current', models.BooleanField(default=True, verbose_name='Актуальный')),
                ('first_name', models.CharField(blank=True, max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=200, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=200, verbose_name='Отчество')),
                ('position', models.CharField(blank=True, max_length=300, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('messenger', models.CharField(blank=True, max_length=300, verbose_name='Мессенджер')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Руководитель')),
                ('department_name', models.CharField(blank=True, max_length=300, verbose_name='Название отдела')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['-current', 'last_name', 'first_name'],
            },
        ),
    ]
