# Generated by Django 5.1.15 on 2026-05-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organizationtag_type_and_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationtag',
            options={'ordering': ['name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='organizationtag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='Код'),
        ),
    ]
