# Generated by Django 5.1.15 on 2026-05-12 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organizationtag_slug_allow_unicode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityFieldChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=120, verbose_name='Поле')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('source', models.CharField(choices=[('manual', 'Ручное изменение'), ('bulk', 'Массовое изменение'), ('sync', 'Синхронизация')], default='manual', max_length=20, verbose_name='Источник')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда изменено')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_field_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_changes', to='organizations.contact', verbose_name='Контакт')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_changes', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Изменение поля',
                'verbose_name_plural': 'Изменения полей',
                'ordering': ['-changed_at', '-id'],
                'indexes': [models.Index(fields=['organization', '-changed_at'], name='organizatio_organiz_68d36a_idx'), models.Index(fields=['contact', '-changed_at'], name='organizatio_contact_7a73ce_idx')],
            },
        ),
    ]
