# Generated by Django 5.1.15 on 2026-06-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_import_batch'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='importbatchrecord',
            new_name='organizatio_batch_i_7746db_idx',
            old_name='organizatio_batch_i_6f0b0d_idx',
        ),
    ]
